### ISSUE TITLE
Accessing a video from Vimeo with the <video> tag

### ISSUE THREAD

**Issue by QPORIT** [vimeo/vimeo-webvr-demo#3]
I do not understand the documentation for using the API to acquire a file for use on a web page. Ultimately I want to use my website and play 360 3D files as in the demo.

To understand the API, and how to use it on a website, what is the simplest way to convert the following HTML, which plays the video (badly) from my website:

<html>
<head>Video from my website</head>
<body>
<br>
<video width="640" height="480" controls>
<source src="http://www.qporit.com/v3/ud/textures/July4.mp4" type="video/mp4">
</video>
<body>
<html>

and create code which will acquire the token automatically, and play the file from Vimeo.  (I have exactly the same file on Vimeo.)

Just to be clear: this step is to understand how to use the API, the next step would be to take all the relevant code necessary to play the video from Vimeo in 360 3D.  (I can play July4.mp4 from my website in 3D 360 but it plays very badly: www.qporitxr.com/v3/ud/vidud.html  .)

**Comment by caseypugh** [comment]
This plugin is built on top of [Node.js](https://github.com/nodejs/node). This requires some basic understanding of server side technology, which is outside the realm of support I can provide you. Your web host also needs to support Node.js. It can get complicated depending on your host's setup, which is why Glitch is a convenient tool for demoing something like this.

However, I'm happy to point you in the right direction on how to set that up on your own website... here are a few resources:
* https://stackoverflow.com/questions/7049789/how-do-i-install-node-js-on-my-dedicated-server
* https://github.com/nodejs/node/wiki

I hope this helps... if you have more questions, I suggest you post a question to Stack Overflow on how to get Node running on your server.
